import prisma from '@/lib/prisma';
import { betterAuth } from 'better-auth';
import { prismaAdapter } from 'better-auth/adapters/prisma';
import { admin, organization } from 'better-auth/plugins';

export const auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: 'postgresql', // or "mysql", "postgresql", ...etc
    usePlural: true,
  }),
  trustedOrigins: ['http://localhost:*'],
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: true, // Set to false if you don't want to require email verification
    revokeSessionsOnPasswordReset: true, // Set to false if you don't want to revoke sessions on password reset
  },
  user: {
    changeEmail: {
      enabled: true, // Set to false if you don't want to allow users to change their email
    },
  },
  plugins: [
    admin(),
    organization(),
    // openAPI({
    //   path: '/auth', // Optional path prefix for the OpenAPI endpoints. The default is "/reference", which means the endpoints will be available at "/api/auth/reference". You can change this to any path you want, but it should be different from the path used by Scalar's API reference plugin (if you're using it) to avoid conflicts. For example, you could set this to "/auth-docs" to have the OpenAPI endpoints available at "/api/auth/auth-docs". Note that this path is relative to the base path of your API, so if your API is served at "/api", the full path will be "/api/auth" by default.
    //   disableDefaultReference: true, // Disable the default reference page generated by Scalar
    // }),
  ],
});
