export const AUTH_REPOSITORY_TOKENS = {
  REFRESH_TOKEN_REPOSITORY: 'REFRESH_TOKEN_REPOSITORY',
  LOGIN_ATTEMPT_REPOSITORY: 'LOGIN_ATTEMPT_REPOSITORY',
  ORGANIZATION_REPOSITORY: 'ORGANIZATION_REPOSITORY',
  EMAIL_SERVICE: 'EMAIL_SERVICE',
};
