export enum LoginFailureReasonEnum {
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
}

export const LOGIN_FAILURE_REASON_VALUES = Object.values(
  LoginFailureReasonEnum,
);
